[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
cardona = "https://rpc.cardona.zkevm-rpc.com"
linea = "https://rpc.goerli.linea.build"
optimismsepolia = "https://optimism-sepolia.drpc.org"
zircuit = "https://zircuit1.p2pify.com/"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
